### PR TITLE
Feedback from sil and others

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
image
image

### CODE REVIEW

**Comment by chrisvire** [comment]
What should I be reviewing?

**Comment by NullVoxPopuli** [comment]
@chrisvire I guess the screenshots?

**Comment by NullVoxPopuli** [comment]
latest status styles:
image

**Comment by NullVoxPopuli** [comment]
Latest toast style: 
image

**Comment by chrisvire** [comment]
Which aspects of the screen shot?  It would be nice to have a bullet list of the things you changed.

BTW, the green color on the toast is obnoxious.
The gray oval look less like buttons.  Maybe Josh should give some input?
Private icon is fine.

Anything else I should be noticing?

**Comment by NullVoxPopuli** [comment]
image


what about that?


The list:
 - new tasks list
 - private projects no longer have a blue background
 - new toasts

**Comment by NullVoxPopuli** [comment]
image

**Comment by NullVoxPopuli** [comment]
I added fixes to 30930 and 30370 as well (they were small)
all that's remaining is fixing the tests for product selection, cause they were tied to order...
just need to update them to select products by name instead of by index.

**Comment by chrisvire** [comment]
LGTM (after tests pass)

**Pull request merged**
