### PR TITLE
Fix Duplicate Products

### PR DESCRIPTION
**Pull request by garrett-hopper**
Process OrbitJS request queue prior to ingesting SignalR data.

### CODE REVIEW

**Comment by garrett-hopper** [comment]
I've been using this script (copy/paste into DevTools console) to continuously add/remove products until they're duplicated to test this.
```js
(async () => {
  const add = [...document.querySelectorAll('button')].find(x => x.innerHTML.includes('Add Products'));
  const remove = [...document.querySelectorAll('button')].find(x => x.innerHTML.includes('Remove Products'));

  const event = document.createEvent("SVGEvents");
  event.initEvent("click", true, true);

  while ([...document.querySelectorAll('div[data-test-project-product-item="true"]')].length < 2) {
    if ([...document.querySelectorAll('div[data-test-project-product-item="true"]')].length > 0) {
      remove.click();
      await new Promise(resolve => setTimeout(resolve, 250));
      const removeProduct = document.querySelectorAll('div[data-test-item="true"]')[0];
      removeProduct.click();
      await new Promise(resolve => setTimeout(resolve, 250));
      document.querySelector('svg.close-modal').dispatchEvent(event);
      await new Promise(resolve => setTimeout(resolve, 250));
    }

    console.clear();
    add.click();
    await new Promise(resolve => setTimeout(resolve, 250));
    const product = [...document.querySelectorAll('div[data-test-item="true"]')].find(x => x.innerHTML.includes('Amazon S3 Bucket'));
    product.click();
    await new Promise(resolve => setTimeout(resolve, 250));
    const store = [...document.querySelectorAll('div[data-test-item="true"]')].find(x => x.innerHTML.includes('wycliffeusa_s3'));
    store.click();
    await new Promise(resolve => setTimeout(resolve, 250));
    document.querySelector('svg.close-modal').dispatchEvent(event);
    await new Promise(resolve => setTimeout(resolve, 250));
  }
})();
```

**Comment by chrisvire** [comment]
@garrett-hopper It looked like the FrontEnd tests had failed, but upon review, we have one test that intermittently fails.  I reran the test and it worked fine.

**Comment by garrett-hopper** [comment]
👍🏻 Thanks for taking care of that.

**Comment by chrisvire** [comment]
👍 

The builds tasks failed due to not being able to push to ECR (and we don't for PRs).  I will fix that.

**Pull request merged**
